services:
  db:
    image: postgres:16
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: platform_db
    volumes:
      - ./.postgres:/var/lib/postgresql/data
      - ./init_tenant_db.sql:/docker-entrypoint-initdb.d/init_tenant_db.sql

